"""bot-users table

Revision ID: 78f9af96faaa
Revises: c901e5cb381e
Create Date: 2019-09-17 18:03:44.579335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78f9af96faaa'
down_revision = 'c901e5cb381e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=34), nullable=True),
    sa.Column('token', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_user_token'), 'bot_user', ['token'], unique=True)
    op.create_index(op.f('ix_bot_user_user_id'), 'bot_user', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_user_user_id'), table_name='bot_user')
    op.drop_index(op.f('ix_bot_user_token'), table_name='bot_user')
    op.drop_table('bot_user')
    # ### end Alembic commands ###
