"""failed_urls table renamed into failed_links

Revision ID: 7922b826e39e
Revises: b2a6464de564
Create Date: 2019-09-17 18:46:24.928699

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7922b826e39e'
down_revision = 'b2a6464de564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=128), nullable=True),
    sa.Column('error', sa.String(length=32), nullable=True),
    sa.Column('message', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_links_error'), 'failed_links', ['error'], unique=False)
    op.create_index(op.f('ix_failed_links_link'), 'failed_links', ['link'], unique=True)
    op.create_index(op.f('ix_failed_links_timestamp'), 'failed_links', ['timestamp'], unique=False)
    op.drop_index('ix_failed_urls_error', table_name='failed_urls')
    op.drop_index('ix_failed_urls_timestamp', table_name='failed_urls')
    op.drop_index('ix_failed_urls_url', table_name='failed_urls')
    op.drop_table('failed_urls')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_urls',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('error', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('message', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_index('ix_failed_urls_url', 'failed_urls', ['url'], unique=True)
    op.create_index('ix_failed_urls_timestamp', 'failed_urls', ['timestamp'], unique=False)
    op.create_index('ix_failed_urls_error', 'failed_urls', ['error'], unique=False)
    op.drop_index(op.f('ix_failed_links_timestamp'), table_name='failed_links')
    op.drop_index(op.f('ix_failed_links_link'), table_name='failed_links')
    op.drop_index(op.f('ix_failed_links_error'), table_name='failed_links')
    op.drop_table('failed_links')
    # ### end Alembic commands ###
