"""renamed tables

Revision ID: b2a6464de564
Revises: 78f9af96faaa
Create Date: 2019-09-17 18:06:44.948369

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b2a6464de564'
down_revision = '78f9af96faaa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=34), nullable=True),
    sa.Column('token', sa.String(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_users_token'), 'bot_users', ['token'], unique=True)
    op.create_index(op.f('ix_bot_users_user_id'), 'bot_users', ['user_id'], unique=True)
    op.create_table('failed_urls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('error', sa.String(length=32), nullable=True),
    sa.Column('message', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_urls_error'), 'failed_urls', ['error'], unique=False)
    op.create_index(op.f('ix_failed_urls_timestamp'), 'failed_urls', ['timestamp'], unique=False)
    op.create_index(op.f('ix_failed_urls_url'), 'failed_urls', ['url'], unique=True)
    op.drop_index('ix_bot_user_token', table_name='bot_user')
    op.drop_index('ix_bot_user_user_id', table_name='bot_user')
    op.drop_table('bot_user')
    op.drop_index('ix_failed_URL_error', table_name='failed_URL')
    op.drop_index('ix_failed_URL_timestamp', table_name='failed_URL')
    op.drop_index('ix_failed_URL_url', table_name='failed_URL')
    op.drop_table('failed_URL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_URL',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('error', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('message', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('timestamp', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_index('ix_failed_URL_url', 'failed_URL', ['url'], unique=True)
    op.create_index('ix_failed_URL_timestamp', 'failed_URL', ['timestamp'], unique=False)
    op.create_index('ix_failed_URL_error', 'failed_URL', ['error'], unique=False)
    op.create_table('bot_user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.VARCHAR(length=34), nullable=True),
    sa.Column('token', mysql.VARCHAR(length=36), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='latin1',
    mysql_engine='MyISAM'
    )
    op.create_index('ix_bot_user_user_id', 'bot_user', ['user_id'], unique=True)
    op.create_index('ix_bot_user_token', 'bot_user', ['token'], unique=True)
    op.drop_index(op.f('ix_failed_urls_url'), table_name='failed_urls')
    op.drop_index(op.f('ix_failed_urls_timestamp'), table_name='failed_urls')
    op.drop_index(op.f('ix_failed_urls_error'), table_name='failed_urls')
    op.drop_table('failed_urls')
    op.drop_index(op.f('ix_bot_users_user_id'), table_name='bot_users')
    op.drop_index(op.f('ix_bot_users_token'), table_name='bot_users')
    op.drop_table('bot_users')
    # ### end Alembic commands ###
