"""failed deletions table

Revision ID: c901e5cb381e
Revises: 
Create Date: 2019-09-05 16:00:40.564299

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c901e5cb381e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('failed_URL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('error', sa.String(length=32), nullable=True),
    sa.Column('message', sa.String(length=64), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_failed_URL_error'), 'failed_URL', ['error'], unique=False)
    op.create_index(op.f('ix_failed_URL_timestamp'), 'failed_URL', ['timestamp'], unique=False)
    op.create_index(op.f('ix_failed_URL_url'), 'failed_URL', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_failed_URL_url'), table_name='failed_URL')
    op.drop_index(op.f('ix_failed_URL_timestamp'), table_name='failed_URL')
    op.drop_index(op.f('ix_failed_URL_error'), table_name='failed_URL')
    op.drop_table('failed_URL')
    # ### end Alembic commands ###
